version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/bssm-aws-react-lecture
books:
  BeforeInstall:
    - location: pull
      timeout: 300
      runas: root
  Install:
    - location: install
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start
      timeout: 300
      runas: root
